name: plugin_binding_demo
description: "A demo of various native binding methods, and measuring their performance"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  jni: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jnigen: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/full_characters.json
    - assets/singlemarkersoriginal.jpg
