name: pull_json
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
